name: guding-loon-script-sync.yml

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取所有历史记录
    
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/Guding88/Script.git
    
    - name: Fetch upstream
      run: |
        git fetch upstream
    
    - name: Sync fork
      run: |
        git checkout main
        git merge upstream/main
        git push origin main
